replicaCount: 1

image:
  repository: gcr.io/cadvisor/cadvisor
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  accessMode: ReadOnlyMany
  size: 1Gi
  storageClassName: "standard"
  readOnly: true

security:
  privileged: false
