apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-config
  labels:
    app: processor
data:
  view.json: |
    {
      "Ingest": {
        "BatchSize": 256,
        "IntervalMs": 5000,
        "MaxConcurrentInsertions": 1
      },
      "Expiration": {
        "BatchSize": 1,
        "IntervalMs": 30000
      },
      "Runtime": {
        "Python": {
          "Version": "3.12",
          "PythonCommandWindows": "C:\\Program Files\\Python312\\python.exe",
          "PythonCommandLinux": "/usr/bin/python3",
          "PythonCommandMac": "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3",
          "PipCommandWindows": "C:\\Program Files\\Python312\\Scripts\\pip.exe",
          "PipCommandLinux": "/usr/bin/pip3",
          "PipCommandMac": "/Library/Frameworks/Python.framework/Versions/3.12/bin/pip3"
        }
      },
      "Shell": {
        "WindowsShell": "cmd.exe",
        "LinuxShell": "bash"
      },
      "CreatedUtc": "2024-12-07T07:38:58.010607Z",
      "CreatedBy": "Setup",
      "SoftwareVersion": "v1.1.0",
      "Node": {
        "GUID": "8bf30e5b-a5e7-4862-9c09-d8a0b0759c4e",
        "Name": "View Processor Server",
        "Hostname": "localhost",
        "InstanceType": "ProcessorServer",
        "LastStartUtc": "2024-12-07T07:38:58.126427Z",
        "CreatedUtc": "2024-12-07T07:38:58.126427Z"
      },
      "Logging": {
        "Servers": [
          {
            "Hostname": "127.0.0.1",
            "Port": 514,
            "RandomizePorts": false,
            "MinimumPort": 65000,
            "MaximumPort": 65535
          }
        ],
        "LogDirectory": "./logs/",
        "LogFilename": "./view.log",
        "ConsoleLogging": true,
        "EnableColors": true,
        "MinimumSeverity": 0
      },
      "Database": {
        "Filename": "./view.db",
        "Type": "Sqlite",
        "Port": 0,
        "Debug": {
          "EnableForQueries": false,
          "EnableForResults": false
        }
      },
      "Server": {
        "Region": "us-west-1",
        "MaxRequestBodySize": 268435456,
        "MaxRangeReadSize": 268435456,
        "HeaderApiKey": "x-api-key",
        "AdminApiKey": "viewsysadmin",
        "TokenExpirationMinutes": 1440
      },
      "Storage": {
        "TempDirectory": "./temp/",
        "CompressionDirectory": "./compress/",
        "MetadataDirectory": "./metadata/",
        "MultipartUploadDirectory": "./multipart/",
        "WebhookRequestDirectory": "./webhookreq/",
        "WebhookResponseDirectory": "./webhookresp/",
        "IngestQueueDirectory": "./ingest/",
        "DataFlowsDirectory": "./dataflows/",
        "DataFlowMapsDirectory": "./dataflowmaps/",
        "DataFlowLogsDirectory": "./dataflowlogs/",
        "PackagesDirectory": "./packages/",
        "BinariesDirectory": "./binaries/",
        "SourceDocumentsDirectory": "./sourcedocs/",
        "ExpirationCheckIntervalSeconds": 60,
        "MaxMultipartUploadSeconds": 86400,
        "BlobDirectory": "./blobs/"
      },
      "Rest": {
        "Hostname": "*",
        "Port": 8000,
        "IO": {
          "StreamBufferSize": 65536,
          "MaxRequests": 1024,
          "ReadTimeoutMs": 10000,
          "MaxIncomingHeadersSize": 65536,
          "EnableKeepAlive": false
        },
        "Ssl": {
          "Enable": false,
          "MutuallyAuthenticate": false,
          "AcceptInvalidAcertificates": true
        },
        "Headers": {
          "IncludeContentLength": true,
          "DefaultHeaders": {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT, POST, DELETE, PATCH",
            "Access-Control-Allow-Headers": "*",
            "Access-Control-Expose-Headers": "",
            "Accept": "*/*",
            "Accept-Language": "en-US, en",
            "Accept-Charset": "ISO-8859-1, utf-8",
            "Cache-Control": "no-cache",
            "Connection": "close",
            "Host": "localhost:8000"
          }
        },
        "AccessControl": {
          "DenyList": {},
          "PermitList": {},
          "Mode": "DefaultPermit"
        },
        "Debug": {
          "AccessControl": false,
          "Routing": false,
          "Requests": false,
          "Responses": false
        }
      },
      "Websocket": {
        "Enable": false,
        "Ssl": false,
        "Hostname": "*",
        "Port": 8003,
        "Prefix": "ws://*:8003/",
        "PermittedIpAddresses": [],
        "HeartbeatIntervalMs": 10000
      },
      "RabbitMq": [],
      "Webhook": {
        "PollIntervalMs": 30000,
        "ResponseRetentionMs": 86400000,
        "BatchSize": 4
      },
      "Control": {
        "AccountGUID": "",
        "SoftwareInstanceGUID": "",
        "Ssl": true,
        "Hostname": "control.view.io",
        "Port": 8403,
        "LogProxy": {
          "Hostname": "127.0.0.1",
          "Port": 65099,
          "RandomizePorts": true,
          "MinimumPort": 65000,
          "MaximumPort": 65535
        },
        "Prefix": "wss://control.view.io:8403/",
        "LogDirectory": "./controllog/",
        "ApiUsageDirectory": "./controlapi/",
        "TokensGeneratedDirectory": "./controltoken/",
        "LogDrainIntervalMs": 60000,
        "ApiUsageDrainIntervalMs": 60000,
        "TokenUsageDrainIntervalMs": 60000
      },
      "Encryption": {
        "Key": "0000000000000000000000000000000000000000000000000000000000000000",
        "Iv": "00000000000000000000000000000000",
        "Salt": "00000000000000000000000000000000"
      },
      "Debug": {
        "Authentication": false,
        "Locks": false,
        "Exceptions": false,
        "Requests": false,
        "Enumeration": false,
        "SearchQueries": false,
        "DatabaseQueries": false,
        "ProcessorRequests": false,
        "ProcessorResponses": false,
        "Broadcasts": false
      }
    }
