app:
  name: view-crawler

replicaCount: 1

image:
  repository: viewio/view-crawler
  tag: v1.1.0
  pullPolicy: IfNotPresent

service:
  name: view-crawler-service
  type: ClusterIP
  port: 8101
  targetPort: 8101

env:
  VIEW_ACCOUNT_GUID: "00000000-0000-0000-0000-000000000000"
  VIEW_DATABASE_TYPE: "Mysql"
  VIEW_DATABASE_HOST: "mysql"
  VIEW_DATABASE_PORT: 3306
  VIEW_DATABASE_NAME: "view"
  VIEW_DATABASE_USER: "root"
  VIEW_DATABASE_PASS: "password"
  VIEW_CONSOLE_LOGGING: "1"
  VIEW_CONTROL_HOSTNAME: "control.view.io"
  VIEW_CONTROL_PORT: 8403
  VIEW_CONTROL_SSL: "true"
  VIEW_CONTROL_SWVERSION: "v1.0.0"
  TERM: "xterm-256color"

persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteMany
  size: 10Gi

pvc:
  name: view-crawler-pvc

volumes:
  mounts:
    - /app/assets
    - /app/logs
    - /app/temp
    - /app/files
    - /app/enumerations
    - /app/webhookreq
    - /app/webhookresp
    - /app/controllog
    - /app/controlapi
    - /app/controltoken

