apiVersion: v2
name: view-io
description: A Helm chart for deploying the view.io dashboard
version: 0.1.0
appVersion: "v1.1.0"

dependencies:
  - name: mysql
    version: 0.1.0
  - name: rabbitmq
    version: 0.1.0
  - name: pgvector
    version: 0.1.0
  - name: view-vector
    version: 0.1.0
  - name: view-ollama
    version: 0.1.0
  - name: view-orchestrator
    version: 0.1.0
  - name: processor
    version: 0.1.0
  - name: view-storage
    version: 0.1.0
  - name: switchboard
    version: 0.1.0
  - name: syslogserver
    version: 0.1.0
  - name: view-assistant
    version: 0.1.0
  - name: view-cadvisor
    version: 0.1.0
  - name: view-config
    version: 0.1.0
  - name: crawler
    version: 0.1.0
#  - name: view-director
#    version: 0.1.0
  - name: view-embeddings
    version: 0.1.0
  - name: view-lexi
    version: 0.1.0
  - name: litegraph
    version: 1.0.0
