replicaCount: 1  # Default replica count

image:
  repository: "viewio/view-orchestrator"
  tag: "v1.1.0"
  pullPolicy: "IfNotPresent"

service:
  port: 8501
  type: "ClusterIP"

env:
  VIEW_ACCOUNT_GUID: "00000000-0000-0000-0000-000000000000"
  VIEW_DATABASE_TYPE: "Mysql"
  VIEW_DATABASE_HOST: "mysql"
  VIEW_DATABASE_PORT: 3306
  VIEW_DATABASE_NAME: "view"
  VIEW_DATABASE_USER: "root"
  VIEW_DATABASE_PASS: "password"
  VIEW_CONSOLE_LOGGING: 1
  VIEW_CONTROL_HOSTNAME: "control.view.io"
  VIEW_CONTROL_PORT: 8403
  VIEW_CONTROL_SSL: "true"
  VIEW_CONTROL_SWVERSION: "v1.0.0"
  TERM: "xterm-256color"

persistence:
  enabled: true
  storageClass: "standard"
  accessModes:
    - "ReadWriteMany"
  size: "5Gi"

volumeMounts:
  config:
    name: "config-volume"
    mountPath: "/app/config"
    subPath: "view.json"
  shared:
    - name: "shared-storage"
      mountPath: "/app/assets"
      subPath: "assets"
    - name: "shared-storage"
      mountPath: "/app/logs"
      subPath: "logs"
    - name: "shared-storage"
      mountPath: "/app/dataflowlogs"
      subPath: "dataflowlogs"
    - name: "shared-storage"
      mountPath: "/app/dataflowmaps"
      subPath: "dataflowmaps"
    - name: "shared-storage"
      mountPath: "/app/packages"
      subPath: "packages"
    - name: "shared-storage"
      mountPath: "/app/ingest"
      subPath: "ingest"
    - name: "shared-storage"
      mountPath: "/app/webhookreq"
      subPath: "webhookreq"
    - name: "shared-storage"
      mountPath: "/app/webhookresp"
      subPath: "webhookresp"
    - name: "shared-storage"
      mountPath: "/app/controllog"
      subPath: "controllog"
    - name: "shared-storage"
      mountPath: "/app/controlapi"
      subPath: "controlapi"
    - name: "shared-storage"
      mountPath: "/app/controltoken"
      subPath: "controltoken"

container:
  name: "orchestrator"
  port: 8501

dependencies:
  mysql:
    name: "mysql"
    enabled: true
  rabbitmq:
    name: "rabbitmq"
    enabled: true