apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: vector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.volumeMounts.config.name }}
              mountPath: {{ .Values.volumeMounts.config.mountPath }}
              subPath: {{ .Values.volumeMounts.config.subPath }}
              readOnly: {{ .Values.volumeMounts.config.readOnly }}
            {{- if .Values.volumeMounts.data.paths }}
            {{- range .Values.volumeMounts.data.paths }}
            - name: {{ $.Values.volumeMounts.data.name }}
              mountPath: {{ . }}
            {{- end }}
            {{- end }}
      volumes:
        - name: {{ .Values.volumeMounts.config.name }}
          configMap:
            name: {{ .Chart.Name }}-config
            items:
                - key: view.json
                  path: view.json
        - name: {{ .Values.volumeMounts.data.name }}
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
