replicaCount: 1

image:
  repository: ankane/pgvector
  tag: latest
  pullPolicy: IfNotPresent

env:
  POSTGRES_DB: "vectordb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST_AUTH_METHOD: "password"
  VIEW_ACCOUNT_GUID: "00000000-0000-0000-0000-000000000000"
  VIEW_DATABASE_TYPE: "Mysql"
  VIEW_DATABASE_FILE: "view.db"
  VIEW_DATABASE_HOST: "mysql"
  VIEW_DATABASE_PORT: "3306"
  VIEW_DATABASE_NAME: "view"
  VIEW_DATABASE_USER: "root"
  VIEW_DATABASE_PASS: "password"
  VIEW_CONSOLE_LOGGING: "1"
  VIEW_CONTROL_HOSTNAME: "control.view.io"
  VIEW_CONTROL_PORT: "8403"
  VIEW_CONTROL_SSL: "true"
  VIEW_CONTROL_SWVERSION: "v1.0.0"

db:
  user: "my_user"
  password: "my_password"

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432
