apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Chart.Name }}-orchestrator
  ports:
      - protocol: TCP
        port: {{ .Values.service.port }}
        targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}