replicaCount: 1  # Processor instances

image:
  repository: viewio/view-processor
  tag: v1.1.0
  pullPolicy: IfNotPresent

service:
  name: processor
  type: ClusterIP
  port: 8403
  targetPort: 8403

env:
  VIEW_ACCOUNT_GUID: "00000000-0000-0000-0000-000000000000"
  VIEW_DATABASE_TYPE: "Mysql"
  VIEW_DATABASE_FILE: "view.db"
  VIEW_DATABASE_HOST: "mysql"
  VIEW_DATABASE_PORT: "3306"
  VIEW_DATABASE_NAME: "view"
  VIEW_DATABASE_USER: "root"
  VIEW_DATABASE_PASS: "password"
  VIEW_CONSOLE_LOGGING: "1"
  VIEW_CONTROL_HOSTNAME: "control.view.io"
  VIEW_CONTROL_PORT: "8403"
  VIEW_CONTROL_SSL: "true"
  VIEW_CONTROL_SWVERSION: "v1.0.0"
  TERM: "xterm-256color"

persistence:
  enabled: true
  storageClass: "standard"
  size: 1Gi
  accessMode: ReadWriteMany
  claimName: processor-pvc

volumes:
  configMapName: processor-config
  sharedStorageName: shared-storage
  mountPaths:
    - path: /app/config
      subPath: view.json
      readOnly: false
    - path: /app/assets
      subPath: assets
    - path: /app/logs
      subPath: logs
    - path: /app/temp
      subPath: temp
    - path: /app/dataflowlogs
      subPath: dataflowlogs
    - path: /app/metadata
      subPath: metadata
    - path: /app/webhookreq
      subPath: webhookreq
    - path: /app/webhookresp
      subPath: webhookresp
    - path: /app/controllog
      subPath: controllog
    - path: /app/controlapi
      subPath: controlapi
    - path: /app/controltoken
      subPath: controltoken