# values.yaml
replicaCount: 1

image:
  repository: viewio/view-assistant
  tag: v1.1.0
  pullPolicy: IfNotPresent

dnsConfig:
  nameservers:
    - 127.0.0.11
    - 8.8.8.8

env:
  VIEW_ACCOUNT_GUID: "00000000-0000-0000-0000-000000000000"
  VIEW_DATABASE_TYPE: "Mysql"
  VIEW_DATABASE_HOST: "mysql"
  VIEW_DATABASE_PORT: "3306"
  VIEW_DATABASE_NAME: "view"
  VIEW_DATABASE_USER: "root"
  VIEW_DATABASE_PASS: "password"
  VIEW_CONSOLE_LOGGING: "1"
  VIEW_CONTROL_HOSTNAME: "control.view.io"
  VIEW_CONTROL_PORT: "8403"
  VIEW_CONTROL_SSL: "true"
  VIEW_CONTROL_SWVERSION: "v1.0.0"
  EMBEDDINGS_PRELOAD_MODELS: "all-MiniLM-L6-v2"
  CORS_ORIGINS: "*"
  HF_HOME: "/app/models/"
  TERM: "xterm-256color"

service:
  type: ClusterIP
  port: 8000


resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

persistence:
  enabled: true
  storageClass: "standard"
  accessModes:
    - ReadWriteMany
  size: "5Gi"

volumeMounts:
  - name: "config-volume"
    mountPath: "/app/config"
    subPath: "view.json"
  - name: "shared-storage"
    mountPath: "/app/assets"
    subPath: "assets"
  - name: "shared-storage"
    mountPath: "/app/logs"
    subPath: "logs"

volumes:
  - name: "config-volume"
    configMap:
      name: "config-volume"
  - name: "shared-storage"
    persistentVolumeClaim:
      claimName: "shared-pvc"
