replicaCount: 1

image:
  repository: viewio/view-config
  tag: v1.1.0
  pullPolicy: IfNotPresent

service:
  name: view-config
  type: ClusterIP
  port: 8601
  targetPort: 8601

env:
  VIEW_ACCOUNT_GUID: "00000000-0000-0000-0000-000000000000"
  VIEW_DATABASE_TYPE: "Mysql"
  VIEW_DATABASE_FILE: "view.db"
  VIEW_DATABASE_HOST: "mysql"
  VIEW_DATABASE_PORT: 3306
  VIEW_DATABASE_NAME: "view"
  VIEW_DATABASE_USER: "root"
  VIEW_DATABASE_PASS: "password"
  VIEW_CONSOLE_LOGGING: "1"
  VIEW_CONTROL_HOSTNAME: "control.view.io"
  VIEW_CONTROL_PORT: 8403
  VIEW_CONTROL_SSL: "true"
  VIEW_CONTROL_SWVERSION: "v1.0.0"
  TERM: "xterm-256color"

persistence:
  enabled: true
  name: shared-pvc
  storageClassName: "standard"
  accessMode: ReadWriteMany
  size: 10Gi
  mountPaths:
    - /app/assets
    - /app/blobs
    - /app/logs
    - /app/webhookreq
    - /app/webhookresp
    - /app/controllog
    - /app/controlapi
    - /app/controltoken

