apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              subPath: view.json
            {{- range .Values.volumes.mounts }}
            - name: shared-storage
              mountPath: {{ . }}
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}-config
        - name: shared-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
