apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.embeddings.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.embeddings.image.repository }}:{{ .Values.embeddings.image.tag }}"
          imagePullPolicy: {{ .Values.embeddings.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.embeddings.port }}
          env:
            {{- range $key, $value := .Values.embeddings.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: embeddings-storage
              mountPath: "{{ .Values.embeddings.storage.mountPath }}"
          stdin: true
          tty: true
      volumes:
        - name: embeddings-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
      restartPolicy: Always
