apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}
