apiVersion: v1
kind: Service
metadata:
  name: litegraph
spec:
  selector:
    app: litegraph
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
