apiVersion: v1
kind: Service
metadata:
  name: ollama-cpu
spec:
  selector:
    app: ollama-cpu
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
  {{- if .Values.ollamaGPU.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ollama-gpu
spec:
  selector:
    app: ollama-gpu
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  {{- end }}
