{{- range .Values.nginxServices }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        limit_req_zone $binary_remote_addr zone=mylimit:10m rate=16r/s;

        proxy_intercept_errors on;

        log_format custom '[$time_local] $remote_addr $request: $status, $body_bytes_sent bytes $http_x_forwarded_for';
        access_log /var/log/nginx/{{ .name }}-access.log custom;
        error_log /var/log/nginx/{{ .name }}-error.log debug;

        client_max_body_size 384M;

        server {
            listen {{ .port | default "8000" }};  # Default to 8000 if no port is specified

            location / {
                limit_req zone=mylimit burst=16 delay=8;

                proxy_pass http://{{ .name }}:{{ .port | default "8000" }};
                proxy_pass_request_headers on;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;

                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_send_timeout 300;
                send_timeout 300;
            }

            add_header X-Response-Inner "{{ .name }}" always;

            error_page 502 /bad_gateway.html;
            location = /bad_gateway.html {
                add_header X-Response-Inner "{{ .name }}" always;
                internal;
                return 502 "Bad Gateway";
            }

            error_page 429 /too_many_requests.html;
            location = /too_many_requests.html {
                add_header X-Response-Inner "{{ .name }}" always;
                internal;
                return 429 "Too Many Requests";
            }        
        }
    }
---
{{- end }}