apiVersion: apps/v1
kind: Deployment
metadata:
  name: switchboard
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: switchboard
  template:
    metadata:
      labels:
        app: switchboard
    spec:
      containers:
        - name: switchboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: {{ .Values.volumeMounts.configVolume.name }}
              mountPath: "{{ .Values.volumeMounts.configVolume.mountPath }}"
              subPath: "{{ .Values.volumeMounts.configVolume.subPath }}"
            - name: {{ .Values.volumeMounts.logVolume.name }}
              mountPath: "{{ .Values.volumeMounts.logVolume.mountPath }}"
      volumes:
        - name: config-volume
          configMap:
            name: "{{ .Values.volumes.configVolume.configMapName }}"

        - name: log-volume
          persistentVolumeClaim:
            claimName: "{{ .Values.persistence.pvcName }}"
