apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName | default "rabbitmq-pvc-claim" }}
spec:
  accessModes:
    {{- .Values.persistence.accessModes | toYaml | nindent 8 }}
  resources:
    requests:
      storage: {{ .Values.persistence.resources.requests.storage | default "1Gi" }}
  storageClassName: {{ .Values.persistence.storageClassName | default "standard" }}
