apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpPort }}
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
    - name: stomp
      port: {{ .Values.service.stompPort }}
      targetPort: {{ .Values.service.stompPort }}
