apiVersion: v1
entries:
  litegraph:
  - apiVersion: v2
    created: "2025-02-12T10:44:34.496805576+05:30"
    description: A Helm chart for deploying LiteGraph
    digest: 16dba714c418a56b5a80750c0b650e165d75eda7f93a303ec06f0ac3e1d8258d
    maintainers:
    - email: hellohello8524@gmail.com
      name: suresh
    name: litegraph
    type: application
    urls:
    - litegraph-1.0.0.tgz
    version: 1.0.0
generated: "2025-02-12T10:44:34.494111775+05:30"
