apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: pgvector-config
              subPath: init.sql
            - mountPath: /var/lib/postgresql/data
              name: pgvector-storage
      volumes:
        - name: pgvector-config
          configMap:
            name: {{ .Chart.Name }}-config
            items:
                - key: init.sql
                  path: init.sql
        - name: pgvector-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
