apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  rabbitmq.conf: |
    loopback_users = none
    listeners.tcp.default = {{ .Values.service.amqpPort }}
    management.tcp.port = {{ .Values.service.managementPort }}
    management.load_definitions = /etc/rabbitmq/definitions.json
    vm_memory_high_watermark.relative = 0.8
    disk_free_limit.absolute = 2GB
    log.file.level = info
    mqtt.listeners.tcp.default = 1883
    web_mqtt.tcp.port = 15675
    web_mqtt.ws_path = /ws
    prometheus.tcp.port = 15692
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-plugins-config
data:
  enabled-plugins: |
    [rabbitmq_management,rabbitmq_mqtt,rabbitmq_web_mqtt,rabbitmq_prometheus].

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-definitions-config
data:
  definitions.json: |
    {
      "users": [
        {
          "name": "guest",
          "password_hash": "BMfxN8drrYcIqXZMr+pWTpDT0nMcOagMduLX0bjr4jwud/pN",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "guest",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "topic_permissions": [],
      "parameters": [],
      "global_parameters": [
        {
          "name": "cluster_name",
          "value": "rabbit@rabbitmq"
        }
      ],
      "policies": [],
      "queues": [],
      "exchanges": [],
      "bindings": []
    }
