apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.amqpPort }}
            - containerPort: {{ .Values.service.managementPort }}
            - containerPort: {{ .Values.service.stompPort }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_port_connectivity"]
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          volumeMounts:
            {{- range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            - name: config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
            - name: plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
            - name: definitions
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json

      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName | default "rabbitmq-pvc-claim" }}
        - name: config
          configMap:
            name: {{ .Chart.Name }}-config
            items:
            - key: rabbitmq.conf
              path: rabbitmq.conf
        - name: plugins
          configMap:
            name: {{ .Chart.Name }}-plugins-config
            items:
            - key: enabled-plugins
              path: enabled_plugins
        - name: definitions
          configMap:
            name: {{ .Chart.Name }}-definitions-config
            items:
            - key: definitions.json
              path: definitions.json