apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
