apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | join ", " }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
